### ISSUE TITLE
Add an AppBar for after-login pages

### ISSUE THREAD

**Issue by slhmy** [OJ-lab/oj-lab-front#4]
Normally an AppBar can float above in most of the site pages (or in another word, it is shared by many pages).

To realize this effect, we can refer to https://github.com/coder/coder/blob/main/site/src/AppRouter.tsx.

**Comment by mareeekb1** [comment]
Hello, can I take this one ?

**Comment by slhmy** [comment]
Please try to consider implementing the AuthAndFrame component like 'coder' do.

Differences may be we are using `redux` instead of `xstate`.
