### ISSUE TITLE
Add mock service

### ISSUE THREAD

**Issue by slhmy** [OJ-lab/oj-lab-front#8]
The missing of backend service is blocking frontend developing now.

For example, the lack of `GetCurrentUser`, is blocking our sign in and redirect step in frontend.
Also, I don't want to make back & front strongly relied, this can be confusing when there is people who just want to join in one of them (the environment preparing can be difficult).

**Comment by slhmy** [comment]
I don't like MockJS for it not updated and only block AJAX, so I'm more likely to make it a simple one...

**Comment by KanadeSiina** [comment]
I'd like to use msw for the mock service, which does not only work for AJAX, but for REST API.
It would be more convenient for the development of the front end without depending on the backend developing progress.
